module.exports.fieldNames = [
  "Maple Grove Field",
  "Riverfront Soccer Park",
  "Northside Athletic Grounds",
  "Cedar Valley Pitch",
  "Lakeside Sports Complex",
  "Mountain View Turf",
  "Evergreen Soccer Centre",
  "Westwood Field",
  "Highland Park Pitch",
  "Sunset Ridge Grounds",
  "Oakwood Athletic Park",
  "Pinecrest Field",
  "Silver Lake Turf",
  "Greenfield Community Park",
  "Prairie Winds Soccer Field",
  "Blue Sky Athletic Complex",
  "Harbourview Pitch",
  "Redwood Sports Grounds",
  "Summit Soccer Park",
  "Valley Creek Field",
  "Golden Mile Turf",
  "Willowbrook Pitch",
  "Eastgate Athletic Park",
  "Grandview Soccer Grounds",
  "Centennial Field",
  "Liberty Sports Complex",
  "Kingsway Turf",
  "Victoria Park Pitch",
  "Forest Hill Soccer Field",
  "Westshore Athletic Grounds",
  "Brookside Field",
  "Meadowlands Soccer Park",
  "Ironwood Turf",
  "Riverside Athletic Complex",
  "Northgate Field",
  "Southridge Pitch",
  "Canyon Creek Grounds",
  "Harbourfront Soccer Field",
  "Windermere Park",
  "Maple Heights Pitch",
  "Stonebridge Soccer Park",
  "Seaside Turf",
  "Elmwood Athletic Grounds",
  "Falcon Ridge Field",
  "Aurora Soccer Centre",
  "Cobalt Park Pitch",
  "Pioneer Athletic Complex",
  "Thunder Bay Field",
  "Beacon Hill Soccer Park",
  "Pacific Crest Turf"
];
